project:
  type: website

website:
  title: "Rueiyu Chang"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Projects
  page-footer: 
    right: "&copy; 2024, Rueiyu Chang"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    published-title: "last updated"
    code-fold: false
    code-summary: ""
    fontsize: 1.3em

editor: visual

execute: 
  freeze: auto